# params
batch_limit: 50

# tools
basespace_cmd: "/home/ubuntu/tools/basespace"
kraken2_db: "/home/ubuntu/refs/kraken2db/"
nextflow_cmd: "/home/ubuntu/tools/nextflow"
ar_dir: "/home/ubuntu/tools/ar_report_generator"

# analysis commands
ODH_version: "v2.0"
phoenix_version: "v2.0.1"
dryad_version: "3.0.1"

analysis_cmd: ""
analysis_cmd_resume: "-resume"
analysis_cmd_trailing: "-profile docker -entry ANALYSIS --max_memory 7.GB --max_cpus 4"

# ref files
ref_fasta: "/home/ubuntu/refs/ASM211692v1.fasta"

# database versions 
AMRFinderPlus: "Version 2023-04-17.1"
ARG_ANNOT: "Latest version NT v6 July 2019"
ResFinder: "v2.1.0 including until 2023-04-12 commit f46d8fc"
AMRFinder: "v2023-04-17.1"
MLST: "pulled from from PubMLST.org 2023-05-02"