#title info
title: "AR Analysis QC Report"
intro_text: "MultiQC reports summarise analysis results."
report_header_info:
  - Project Type: "AR Analysis"

#clean sample names
fn_clean_exts:
  - ".gz"
  - ".fastq"
  - "_S"
  - "consensus_"
  - "_[0-1]"

kraken:
  contents_re: ^\s{0,2}(\d{1,3}\.\d{1,2})\t(\d+)\t(\d+)\t((\d+)\t(\d+)\t)?([URDKPCOFGS-]\d{0,2})\t(\d+)(\s+)unclassified
  num_lines: 1
  top_n: 5

module order:
        - 'fastQC'
        - 'kraken'