# params
batch_limit: 6
kraken2_contamination_threshold: 20

# tools
basespace_cmd: "/home/ubuntu/tools/basespace"
kraken2_db: "/home/ubuntu/refs/k2/k2_standard_08gb_20240112.tar.gz"
nextflow_cmd: "/home/ubuntu/tools/nextflow"
ar_dir: "/home/ubuntu/tools/ar_report_generator"

# analysis commands
analysis_cmd: "/home/ubuntu/tools/nextflow run /home/ubuntu/workflows/AST_Workflow/tools/phoenix/main.nf"
analysis_cmd_trailing: "-profile docker -entry PHOENIX_ODHL --max_memory 7.GB --max_cpus 4"
tree_cmd_trailing: "-profile docker -entry TREE --max_memory 7.GB --max_cpus 4"
dbs_cmd_trailing: "-profile docker -entry DBS --max_memory 7.GB --max_cpus 4"

# ref files
ref_fasta: "/home/ubuntu/refs/ASM211692v1.fasta"

# database versions
ODH_version: "v2.0"
phoenix_version: "v2.0.2"
dryad_version: "3.0.1"
AMRFinderPlus: "Version 2023-04-17.1"
ARG_ANNOT: "Latest version NT v6 July 2019"
ResFinder: "v2.1.0 including until 2023-04-12 commit f46d8fc"
AMRFinder: "v2023-04-17.1"
MLST: "pulled from from PubMLST.org 2023-05-02"
config_MetaPhlAn_db: "mpa_vJun23_CHOCOPhlAnSGB_202307"

metadata_file: "METADATAFILE"

logo_file: "odh_logo_240128.png"

# percent ID for tree
percent_id: "90"

###############################
# PARAMS REQUIRED
###############################
################ NCBI (attributes)
geo_loc_name: "USA"
host: "Homo sapiens"
sample_type: "whole organism"

################ NCBI (metadata)
library_strategy: "WGS"
library_source: "Genomic"
library_selection: "Random"
library_layout: "Paired"
platform: "Illumina"
design_description: "WGS by Illumina MiSeq using Illumina DNA Prep library prep"
filetype: "fastq"

###############################
# PARAMS Optional
###############################
############# NCBI (attributes)
altitude: ""
bioproject_accession: "PRJNA288601"
biomaterial_provider: ""
collected_by: "Ohio Department of Health Laboratory"
culture_collection: ""
depth: ""
env_broad_scale: ""
genotype: ""
host_tissue_sampled: ""
identified_by: ""
lab_host: ""
lat_lon: ""
mating_type: ""
passage_history: ""
samp_size: ""
serotype: ""
serovar: ""
specimen_voucher: ""
strain: ""
temp: ""
description: ""